table 未决因子及经验赔付率2数据
	lineageTag: fe3c6971-6cbb-4da8-8195-09a394974774

	column 类别
		dataType: string
		lineageTag: 68e0d713-d469-4b14-9c69-c99bb01e9949
		summarizeBy: none
		sourceColumn: 类别

		annotation SummarizationSetBy = Automatic

	column 区间
		dataType: string
		lineageTag: 0491dc96-dc6c-496a-9d24-3869c857388c
		summarizeBy: none
		sourceColumn: 区间

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: double
		lineageTag: 284c7ae4-9903-4ece-8fbf-d8053ab0a7a2
		summarizeBy: sum
		sourceColumn: Value

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 机构
		dataType: string
		lineageTag: 556d4c2b-e44a-492f-8e68-c8ba786604f5
		summarizeBy: none
		sourceColumn: 机构

		annotation SummarizationSetBy = Automatic

	column Key
		type: calculated
		lineageTag: fa1af5eb-2c81-4684-8393-859efa8006a3
		summarizeBy: count

		annotation SummarizationSetBy = Automatic

	column Period
		dataType: int64
		formatString: 0
		lineageTag: a795e388-1d61-45d9-9212-2ce31236b4ff
		summarizeBy: sum
		sourceColumn: Period

		annotation SummarizationSetBy = Automatic

	partition 未决因子及经验赔付率2数据 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\wa\OneDrive\PBI\reports_for_beer_pbib\填报表单结构.xlsx"), null, true),
				    未决因子及经验赔付率2数据_Sheet = Source{[Item="未决因子及经验赔付率2数据",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(未决因子及经验赔付率2数据_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"类别", type text}, {"区间", type text}, {"Value", type number}, {"机构", type text}}),
				    #"Inserted Text Before Delimiter" = Table.AddColumn(#"Changed Type", "Period", each Text.BeforeDelimiter([区间], "-"), type text),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Inserted Text Before Delimiter",{{"Period", Int64.Type}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type1", each ([类别] = "非健康"))
				in
				    #"Filtered Rows"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

