table 未到期保费数据
	lineageTag: 13a2089d-c040-45e6-9e43-0220d8146bc5

	column 公司类型
		dataType: string
		lineageTag: d76be96f-947d-4010-ae78-6dd27c559530
		summarizeBy: none
		sourceColumn: 公司类型

		annotation SummarizationSetBy = Automatic

	column 法人产品新类别
		dataType: string
		lineageTag: e82bc03e-6b11-45f9-82c0-2136bea09f77
		summarizeBy: none
		sourceColumn: 法人产品新类别

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: double
		lineageTag: bedf6101-5bef-47ed-9c8e-c9d4910bac36
		summarizeBy: sum
		sourceColumn: Value

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Year
		dataType: int64
		formatString: 0
		lineageTag: adca9c5b-743b-420f-a529-77460ac912c0
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		formatString: 0
		lineageTag: 60e24493-52eb-47fc-9950-86a9dcd9fad6
		summarizeBy: sum
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column 机构
		dataType: string
		lineageTag: 9a60f860-c680-42cb-86fb-3d4a0569128d
		summarizeBy: none
		sourceColumn: 机构

		annotation SummarizationSetBy = Automatic

	column Key = '未到期保费数据'[Year]&"-"&'未到期保费数据'[Month]&"-"&'未到期保费数据'[机构]&"-"&'未到期保费数据'[法人产品新类别]
		lineageTag: 462d0bc9-310a-47f7-ab09-5c3229292f16
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 未到期保费数据 = m
		mode: import
		source =
				let
<<<<<<< HEAD
				    Source = Excel.Workbook(File.Contents("C:\Users\wa\OneDrive\PBI\reports_for_beer_pbib\填报表单结构.xlsx"), null, true),
=======
				    Source = Excel.Workbook(File.Contents("D:\Git\reports_for_beer_pbib\填报表单结构.xlsx"), null, true),
>>>>>>> 42d4a0d6831d849109d381b21a3064667447500a
				    未到期保费数据_Sheet = Source{[Item="未到期保费数据",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(未到期保费数据_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"公司类型", type text}, {"法人产品新类别", type text}, {"Value", type number}, {"Year", Int64.Type}, {"Month", Int64.Type}, {"机构", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

