table 经过保费数据
	lineageTag: c6bbad6e-0c3a-4260-8558-992e76374495

	column 经过保费
		dataType: double
		lineageTag: 9c53f984-3eda-4b05-8932-88b5c66a092e
		summarizeBy: none
		sourceColumn: 经过保费

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Date
		dataType: string
		lineageTag: a35ea2ec-b5a9-44e8-8143-5be31dfe8454
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

	column 保单号
		dataType: string
		lineageTag: 03172bf8-c0ca-4c70-a49f-dfc479d99eb7
		summarizeBy: none
		sourceColumn: 保单号

		annotation SummarizationSetBy = Automatic

	partition 经过保费数据 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("D:\Git\reports_for_beer_pbib\填报表单结构.xlsx"), null, true),
				    经过保费数据_Sheet = Source{[Item="经过保费数据",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(经过保费数据_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"法人产品新类别", type text}, {"Value", type number}, {"Year", Int64.Type}, {"Month", Int64.Type}, {"机构", type text}}),
				    #"Filtered Rows2" = Table.SelectRows(#"Changed Type", each ([Year] = 2024) and ([Month] = 1)),
				    #"Inserted Merged Column" = Table.AddColumn(#"Filtered Rows2", "Date", each Text.Combine({Text.From([Year], "zh-CN"), "/", Text.From([Month], "zh-CN"), "/1"}), type text),
				    #"Renamed Columns" = Table.RenameColumns(#"Inserted Merged Column",{{"Value", "经过保费"}}),
				    #"Filtered Rows" = Table.SelectRows(#"Renamed Columns", each ([法人产品新类别] = "非健康险")),
				    #"Removed Other Columns" = Table.SelectColumns(#"Filtered Rows",{"保单号", "经过保费", "Date"}),
				    #"Grouped Rows" = Table.Group(#"Removed Other Columns", {"Date", "保单号"}, {{"经过保费", each List.Sum([经过保费]), type nullable number}}),
				    #"Filtered Rows1" = Table.SelectRows(#"Grouped Rows", each ([Date] = "2024/1/1"))
				in
				    #"Filtered Rows1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

