table 费用支出数据
	lineageTag: 277b0d66-0929-4248-9063-4d668797b3aa

	column 费用支出类型
		dataType: string
		lineageTag: bac67f00-6141-4487-b7d0-cb966b257b8b
		summarizeBy: none
		sourceColumn: 费用支出类型

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: double
		lineageTag: d230f0e9-5756-425e-ba0d-fe074f4792e0
		summarizeBy: sum
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 831472a8-3faa-4876-86e5-6b0e233a2592
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		formatString: 0
		lineageTag: 3686b162-465d-4625-aeed-c3c190688dcd
		summarizeBy: sum
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column 机构
		dataType: string
		lineageTag: 6cc2f39a-0863-4c61-8205-05f8a2245055
		summarizeBy: none
		sourceColumn: 机构

		annotation SummarizationSetBy = Automatic

	column Key = '费用支出数据'[Year]&"-"&'费用支出数据'[Month]&"-"&'费用支出数据'[机构]
		lineageTag: fa425638-35f8-4a89-9c3f-642c786ac9af
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 费用支出数据 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\wa\OneDrive\PBI\新华\填报表单结构.xlsx"), null, true),
				    费用支出数据_Sheet = Source{[Item="费用支出数据",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(费用支出数据_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"费用支出类型", type text}, {"Value", type number}, {"Year", Int64.Type}, {"Month", Int64.Type}, {"机构", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

